### ISSUE TITLE
Format-YAML - seems only the values of properties that are strings get outputted

### ISSUE THREAD

**Issue by dfinke** [StartAutomating/EZOut#58]
```
Import-Excel .\sample.xlsx | Format-YAML
```
[Sample.xlsx](https://github.com/StartAutomating/EZOut/files/9277417/Sample.xlsx)

Only prints the `Category`. The "numbers" don't get emitted for the others.
```
- OrderId: 
  Category: Cosmetics
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Grocery
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Apparels
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Electronics
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Electronics
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Apparels
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Electronics
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Cosmetics
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Grocery
  Sales: 
  Quantity: 
  Discount: 
- OrderId: 
  Category: Grocery
  Sales: 
  Quantity: 
  Discount: 
```
